#!/bin/bash

nmcli con mod "$1" ipv4.addresses 192.168.56.101/24 &
nmcli con mod "$1" ipv4.gateway 192.168.56.1 &
nmcli con mod "$1" ipv4.dns 8.8.8.8 &
nmcli con mod "$1" ipv4.method manual

nmcli con down "$1"
nmcli con up "$1"