#!/bin/bash

nmcli con mod "Wired connection $1" ipv4.addresses 192.168.56.101/24 &
nmcli con mod "Wired connection $1" ipv4.gateway 192.168.56.1 &
nmcli con mod "Wired connection $1" ipv4.dns 8.8.8.8 &
nmcli con mod "Wired connection $1" ipv4.method manual

nmcli con down "Wired connection $1"
nmcli con up "Wired connection $1"